cats99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats

  # get 'cats', to: 'cats#index'
  # get 'cats/:id', to: 'cats#show'
  # post 'cats', to: 'cats#create'
  # patch 'cats/:id', to: 'cats#update'
  # put 'cats/:id', to: 'cats#update'
  # delete 'cats/:id', to: 'cats#destroy'
  # get 'cats/:id/edit', to: 'cats#edit'
  # get 'cats/new', to: 'cats#new'

end

cats99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats99/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birthdate   :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

# require 'ActionView'

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  COLORS = ['white', 'black', 'tabby', 'calico', 'orange']
  validates :color, :name, :sex, :description, :birthdate, presence: true
  validates :sex, inclusion: { in: ['m', 'f'] }
  validates :color, inclusion: { in: COLORS }

  def age
    time_ago_in_words(birthdate)
  end

  has_many :cat_rental_requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy

end

cats99/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
  validates :status, :start_date, :end_date, :cat_id, presence: true
  validates :status, inclusion: { in: ['PENDING','APPROVED','DENIED'] }

  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat

  def overlapping_requests
    test = CatRentalRequest.select('*').joins('cats')
                           .where("cats.id = cat_id")
    p test
  end

end

cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
    # render index_url
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def create
    @cat = Cat.new(cats_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def update
    @cat = Cat.find_by(id: params[:id])

    if @cat.update_attributes(cats_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private
  def cats_params
    params.require(:cat).permit(:name, :birthdate, :color, :sex, :description)
  end

end

cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats99/app/helpers/cats_helper.rb
module CatsHelper
end

cats99/app/views/cats/_form.html.erb
    <!-- Pick method and url
    pre-populate when present
    fix submission name at end -->

  <% if action == :edit %>
    <% form_url = cat_url(cat) %>
  <% else %>
    <% form_url = cats_url %>
  <% end %>

<form action="<%= form_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

<label> Cat Name
<input type='text' id="Name" name="cat[name]" value="<%= cat.name %>" >
</label>

<br><br>

<label> Cat Gender
<br>

Male <input type="radio" name='cat[sex]' value="m" <%= cat.sex == 'm' || cat.sex.nil? ? "checked" : "" %> >
Female <input type="radio" name='cat[sex]' value="f" <%= "checked" if cat.sex == 'f' %>>
</label>
<br><br>

<label for="color"> Cat Color </label>
<select id="color" name='cat[color]' >

<option value="Select Cat Color" disabled="true" <%= cat.color ? "" : "selected" %> >
  Select Cat Color
</option>

<% Cat::COLORS.each do |color| %>
   <option value='<%= color %>' <%= color == cat.color ? "selected" : "" %> >
      <%= color.capitalize %>
   </option>
<% end %>
</select>

<br><br>

<label for='date'> Birthday </label>
<input id='date' type='date' name='cat[birthdate]' value='<%= cat.birthdate %>' >

<h3>Description:</h3>
<textarea name=cat[description]> <%= cat.description %> </textarea>

<input type="submit" value="<%= action == :edit ? 'Edit Cat!' : "Add Cat!" %>">
</form>

cats99/app/views/cats/edit.html.erb
<h1>EDIT THIS CAT!</h1>


<%= render 'form', cat: @cat, action: :edit %>


<br>
<footer>
  <sub><sub><sub><sub><sub><sub>Do Not Abuse Cat Editing</sub></sub></sub></sub></sub></sub>
</footer>

cats99/app/views/cats/index.html.erb
<h1> LOOK AT THESE CATS! </h1>

<% @cats.each do |cat| %>
  <ul>
    <li>
      <%= link_to "Check Out #{cat.name}", cat_url(cat) %>
    </li>
  </ul>
<% end %>

cats99/app/views/cats/new.html.erb
<h1>ADD A CAT!</h1>

<%= render 'form', cat: @cat, action: :new %>

cats99/app/views/cats/show.html.erb
<h1>
<%= @cat.name.capitalize %>
</h1>

<%= button_to "Edit Cat", edit_cat_url(@cat), method: :get %>

<table>
  <thead>
    <tr>
      <th>Attribute</th>
      <th>Information</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Age</td>
      <td><%= @cat.age.capitalize %></td>
    </tr>
  </tbody>
  <tbody>
    <tr>
      <td>Gender</td>
      <td><%= @cat.sex == 'm' ? 'Male' : 'Female' %></td>
    </tr>
  </tbody>
  <tbody>
    <tr>
      <td>Color</td>
      <td><%= @cat.color.capitalize %></td>
    </tr>
  </tbody>
</table>

<h3> Cat Description </h3>
<%= @cat.description %>

<br>
<br>
<%= link_to "Back to Cat List", cats_url %>

cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>

    <!-- <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %> -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>